# Generated by Django 3.2.9 on 2021-12-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
